# services:
#   backend:
#     build: ./MCGI-CHRISTCHURCH-Back-End
#     ports:
#       - "4000:4000"
   

#   frontend:
#     build: ./MCGI-CHRISTCHURCH-Front-End
#     ports:
#       - "3000:3000"
    
      

version: '3.8' # Specify a version
services:
  backend:
    image: maryrosedocker/mcgi-backend:latest
    ports:
      - "4000:4000"

  frontend:
    image: maryrosedocker/mcgi-frontend:latest
    ports:
      - "3000:3000"