name: Lightsail Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub  # Or your container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Or the path to your Dockerfile
          push: true
          tags: maryrosegithub21/mcgifeastcelebration:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Push Container Image to Lightsail
        run: |
          aws lightsail push-container-image \
              --service-name project-one-mcgi \
              --image maryrosegithub21/mcgifeastcelebration:latest \
              --label latest  # Or a more descriptive label